version: '3.8'

services:
  plextv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plextv
    restart: unless-stopped
    ports:
      - "8080:3000"
      - "1900:1900/udp"
    volumes:
      - ./data:/data
    environment:
      - NODE_ENV=production
      - HOST_IP=0.0.0.0
      - HTTP_PORT=3000
      - STREAM_PORT=3000
      - DISCOVERY_PORT=1900
      - PORT=3000
      - DB_PATH=/data/database/plextv.db
      - LOG_PATH=/data/logs
      - CACHE_PATH=/data/cache
      - LOGOS_PATH=/data/logos
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s